"""
The written cells: one object, thirteen cats, thirteen different afternoons.

This is the only content. Every line was written for *that* object shown to
*that* class, and nothing here is assembled from parts or filled in by a
template. There used to be a generator standing in for the objects nobody had
reached; it produced things like "has met an accordion before" and it is gone.
An object that is not in this file simply does nothing when it is shown.

The rules, learned the hard way:

* **It happens in the arena.** A cat cannot "leave the room": there is no room,
  there is a fight, and everyone is watching. It can flinch, hide behind
  something, refuse to look, or get on top of the thing. It cannot exit.
* **It has to be about this object.** If the line would read the same with a
  different noun dropped in, it is filler and does not belong here.
* **It has to be about this cat.** A Loaf and a Zoom Gremlin do not have the
  same afternoon, ever.
* **The stats follow the story.** A cat that got what it wanted goes up in the
  attribute it used to get it. A cat that embarrassed itself goes down.
* Present tense, one thing happening, about a dozen words. No em dashes.

Progress is the number of objects in here against the 1,372 in the catalogue.
The panel shows the same count, so the work left is never in doubt.
"""

from __future__ import annotations

import json
import pathlib as _pathlib


def L(text: str, **stats: int) -> tuple:
    return (text, {k: v for k, v in stats.items() if v})


# Ordered roughly by how likely somebody is to actually react with it.
WRITTEN: dict[str, dict[str, tuple]] = {
    "🐟": {
        "pouncer": L("Takes the fish out of the air before it lands.", strength=2, agility=1),
        "loaf": L("Does not rise for the fish. The fish may be brought.", strength=1, intellect=1),
        "chonk": L("Eats the fish in one and looks for the next fish.", strength=3, agility=-1),
        "ricochet": L("Snatches the fish at a run and skids into a wall.", agility=2, intellect=-1),
        "ghost": L("The fish is gone. Nobody saw the fish go.", agility=2, intellect=1),
        "gremlin": L("Kills the fish again, thoroughly, in case.", strength=2, charm=-1),
        "barger": L("Ignores the fish and works out where fish are kept.", intellect=3),
        "stalker": L("Carries the fish up somewhere high to eat unjudged.", intellect=1, agility=2),
        "purrsuader": L("Gets a second fish out of a spectator without moving.", charm=3, intellect=1),
        "tyrant": L("The fish was always hers. You were holding it for her.", charm=2, strength=1),
        "weaver": L("Winds round the fish holder until the fish drops.", charm=2, agility=1),
        "dinner": L("Eats the fish, then tells everyone she has not been fed.", charm=3, intellect=1),
        "alley": L("Eats the fish fast, with one eye on everyone else.", strength=2, agility=1),
    },
    "🥛": {
        "pouncer": L("Ambushes the glass. The glass tips. Everyone loses.", strength=1, intellect=-1),
        "loaf": L("Drinks the milk slowly, sitting down, eyes shut.", strength=2, intellect=1),
        "chonk": L("Drinks all of it and regrets it in about an hour.", strength=2, agility=-1),
        "ricochet": L("Knocks the milk flying and chases what spills.", agility=2, strength=-1),
        "ghost": L("The level in the glass drops. No cat is near it.", agility=1, intellect=2),
        "gremlin": L("Puts one whole paw in the milk and licks the paw.", charm=1, intellect=-1),
        "barger": L("Gets the lid off the milk without spilling any.", intellect=3),
        "stalker": L("Watches the milk from above and waits to be alone.", intellect=2),
        "purrsuader": L("Looks at the milk, then at you, until it is poured.", charm=3),
        "tyrant": L("Sits beside the milk so nobody else may drink it.", charm=2, strength=1),
        "weaver": L("Winds round the pourer's legs and gets served first.", charm=2, agility=1),
        "dinner": L("Finishes the milk and reports the bowl still empty.", charm=2, intellect=1),
        "alley": L("Drinks the milk quickly. Milk does not come twice.", strength=2, agility=1),
    },
    "🧀": {
        "pouncer": L("Pounces the cheese. Cheese does not run. Slight anticlimax.", strength=1, intellect=-1),
        "loaf": L("Sits beside the cheese and warms it to room temperature.", strength=1, intellect=1),
        "chonk": L("Eats cheese he is not supposed to have and glows.", strength=2, charm=1),
        "ricochet": L("Bats the cheese under the nearest heavy object.", agility=2),
        "ghost": L("Steals the cheese during somebody else's sentence.", agility=2, intellect=1),
        "gremlin": L("Chews the corner off the cheese and abandons it.", strength=1, charm=-1),
        "barger": L("Opens the cheese wrapper. It was not difficult.", intellect=3),
        "stalker": L("Takes the cheese to the top of the fridge.", intellect=2, agility=1),
        "purrsuader": L("Convinces a stranger that she is allowed cheese.", charm=3, intellect=1),
        "tyrant": L("Puts a paw on the cheese. The cheese is now hers.", charm=2, strength=1),
        "weaver": L("Trips the cheese carrier. The cheese hits the floor.", agility=2, charm=1),
        "dinner": L("Cries at the cheese until a piece is handed over.", charm=3),
        "alley": L("Knows cheese is worth having. Takes it and goes.", strength=1, intellect=2),
    },
    "🐭": {
        "pouncer": L("This is the entire reason a Pouncer exists.", strength=3, agility=1),
        "loaf": L("Watches the mouse cross the arena. Stays exactly put.", intellect=2, agility=-1),
        "chonk": L("Gives chase for two metres, then reconsiders everything.", strength=1, agility=-1),
        "ricochet": L("Chases the mouse into a wall at full speed.", agility=2, intellect=-1),
        "ghost": L("Was already between the mouse and the exit.", agility=2, intellect=2),
        "gremlin": L("Catches the mouse and lets it go, to keep the game.", agility=2, intellect=-1),
        "barger": L("Works out which hole the mouse will use. Waits there.", intellect=3),
        "stalker": L("Tracks the mouse from the shelf without moving a whisker.", intellect=2, agility=1),
        "purrsuader": L("Brings the mouse to a human as an unwanted gift.", charm=2, intellect=1),
        "tyrant": L("Expects the mouse to be dealt with by staff.", charm=2, agility=-1),
        "weaver": L("Herds the mouse between everyone's ankles for fun.", agility=2, charm=1),
        "dinner": L("Considers the mouse dinner, then thinks better of it.", charm=1, intellect=1),
        "alley": L("Catches the mouse without ceremony. This is a job.", strength=2, agility=2),
    },
    "🐕": {
        "pouncer": L("Goes for the dog's tail from behind a chair.", strength=2, intellect=-1),
        "loaf": L("Sits still. The dog loses interest first. It always does.", strength=2, intellect=2),
        "chonk": L("Stands his ground because moving is not on the table.", strength=2, agility=-1),
        "ricochet": L("Runs three laps around the dog until it gives up.", agility=3),
        "ghost": L("Is on top of the wardrobe before the dog is through the door.", agility=2, intellect=1),
        "gremlin": L("Boxes the dog on the nose and instantly regrets it.", strength=1, charm=-1),
        "barger": L("Works out the dog is on a lead, and uses the extra metre.", intellect=3),
        "stalker": L("Waits above the dog for as long as it takes.", intellect=2, agility=1),
        "purrsuader": L("Befriends the dog, which is now working for her.", charm=3, intellect=1),
        "tyrant": L("Walks past the dog slowly, to make a point.", charm=2, strength=1),
        "weaver": L("Weaves under the dog and out the other side.", agility=3),
        "dinner": L("Complains at length that the dog gets fed first.", charm=2, intellect=1),
        "alley": L("Has settled things with bigger dogs than this one.", strength=2, intellect=1),
    },
    "🕷️": {
        "pouncer": L("Takes the spider in one paw from four feet away.", strength=2, agility=1),
        "loaf": L("Lets the spider walk across him. Does not comment.", intellect=2),
        "chonk": L("Eats the spider. Sneezes. Considers the matter closed.", strength=1, intellect=-1),
        "ricochet": L("Bats the spider across the arena and loses it.", agility=2, intellect=-1),
        "ghost": L("Studies how the spider waits. Approves of the method.", intellect=2, agility=1),
        "gremlin": L("Eats the spider in front of everyone, maintaining eye contact.", charm=1, strength=1),
        "barger": L("Follows the spider to find where the gap in the wall is.", intellect=3),
        "stalker": L("Watches the spider from above, professional to professional.", intellect=2),
        "purrsuader": L("Screams once and has a human deal with the spider.", charm=2, intellect=1),
        "tyrant": L("Requires that the spider be removed. By somebody else.", charm=2, agility=-1),
        "weaver": L("Follows the spider's thread with one paw, delighted.", agility=2, charm=1),
        "dinner": L("Establishes that the spider is not dinner. Loudly.", charm=1, intellect=-1),
        "alley": L("Eats the spider. Protein is protein.", strength=2, intellect=1),
    },
    "📦": {
        "pouncer": L("Waits inside the box. Everything that passes is prey.", strength=1, agility=2),
        "loaf": L("Fits the box exactly. Will not be leaving the box.", strength=2, intellect=1),
        "chonk": L("Does not fit the box. Wears the box instead.", strength=2, agility=-2),
        "ricochet": L("Enters the box at speed. The box travels.", agility=2, strength=1),
        "ghost": L("The box is empty. The box has never been empty.", agility=1, intellect=2),
        "gremlin": L("Destroys the box in a minute, then mourns the box.", strength=2, charm=-1),
        "barger": L("Opens the flaps from inside. Learns something about doors.", intellect=3),
        "stalker": L("Stands on the box and gains a foot of height.", intellect=2, agility=1),
        "purrsuader": L("Sits in the box looking beautiful until photographed.", charm=3),
        "tyrant": L("Claims the box. There was never any doubt about the box.", charm=2, strength=1),
        "weaver": L("In one end of the box, out the other, twice.", agility=3),
        "dinner": L("Cries from inside the box. The acoustics are excellent.", charm=3),
        "alley": L("A box is a house. Gets in and stops shivering.", strength=1, charm=1),
    },
    "🧶": {
        "pouncer": L("Ambushes the wool from behind and takes it down.", strength=1, agility=2),
        "loaf": L("Rests his chin on the wool. It is a pillow now.", strength=1, intellect=1),
        "chonk": L("Lies on the wool. The wool is not seen again.", strength=2, agility=-1),
        "ricochet": L("Sends the wool across the arena and follows it.", agility=3),
        "ghost": L("The wool unwinds slowly with no cat attached.", intellect=2, agility=1),
        "gremlin": L("Ties three cats together and looks proud.", charm=2, intellect=-1),
        "barger": L("Finds the loose end and pulls the whole thing apart.", intellect=2, strength=1),
        "stalker": L("Drops the wool off a shelf and watches it fall.", intellect=2, agility=1),
        "purrsuader": L("Plays with the wool adorably until somebody joins in.", charm=3),
        "tyrant": L("Sits in the middle of the wool and receives compliments.", charm=2),
        "weaver": L("This is what she is for. Everything gets wound.", charm=2, agility=3),
        "dinner": L("Eats a length of wool. This will be a problem later.", charm=1, intellect=-2),
        "alley": L("Bats the wool once, remembers being a kitten, joins in.", agility=2, charm=1),
    },
    "🔴": {
        "pouncer": L("Pounces the red dot. There is nothing under his paw.", strength=1, intellect=-2),
        "loaf": L("Watches the dot cross the floor. Declines to follow it.", intellect=2),
        "chonk": L("Chases the dot for four seconds and needs a rest.", strength=1, agility=-1),
        "ricochet": L("Follows the dot up a wall and keeps going.", agility=3, intellect=-1),
        "ghost": L("Works out where the dot comes from and stares at the hand.", intellect=3),
        "gremlin": L("Loses his entire mind over a dot on a wall.", agility=2, intellect=-2),
        "barger": L("Traces the beam back and sits on the pointer.", intellect=3),
        "stalker": L("Waits for the dot to come to the shelf. It does.", intellect=2, agility=1),
        "purrsuader": L("Chases the dot only while she is being watched.", charm=2, intellect=1),
        "tyrant": L("Refuses to chase the dot in front of people.", charm=1, agility=-1),
        "weaver": L("Follows the dot round three sets of ankles.", agility=2, charm=1),
        "dinner": L("Believes the dot is food and cannot be talked out of it.", charm=1, intellect=-2),
        "alley": L("Recognises a trick and does not fall for it twice.", intellect=2),
    },
    "🥒": {
        "pouncer": L("Launches at the cucumber and lands somewhere unplanned.", agility=2, strength=-1),
        "loaf": L("Notices the cucumber. Continues sitting on his own feet.", intellect=2),
        "chonk": L("Achieves about a foot of air. It is enormously impressive.", agility=1, strength=-1),
        "ricochet": L("Is airborne before the cucumder touches the floor.", agility=3),
        "ghost": L("Is not where the cucumber was put. Was never there.", agility=2, intellect=1),
        "gremlin": L("Screams, jumps, returns, and bites the cucumber.", agility=2, charm=-1),
        "barger": L("Sniffs the cucumber. Concludes: vegetable. Unimpressed.", intellect=3),
        "stalker": L("Sees the cucumber being placed. The trick fails entirely.", intellect=3),
        "purrsuader": L("Is startled, and makes it everybody else's fault.", charm=2, intellect=1),
        "tyrant": L("Refuses to acknowledge that the jump happened.", charm=2, strength=-1),
        "weaver": L("Hops the cucumber neatly and carries on winding.", agility=2, charm=1),
        "dinner": L("Assumes food, discovers cucumber, is personally insulted.", charm=1, intellect=-1),
        "alley": L("Has been startled by worse things than a vegetable.", strength=1, intellect=1),
    },
    "🧹": {
        "pouncer": L("Ambushes the bristles and wins decisively.", strength=2),
        "loaf": L("Is swept along the floor without changing expression.", strength=1, intellect=1),
        "chonk": L("Is swept around like a rug that has opinions.", strength=1, agility=-1),
        "ricochet": L("Rides the broom, falls off, blames the broom.", agility=1, strength=-1),
        "ghost": L("Is above the broom before the broom arrives.", agility=2, intellect=1),
        "gremlin": L("Declares war on the broom. The broom is unaware.", strength=1, charm=-1),
        "barger": L("Understands the broom, and fears it correctly.", intellect=2, charm=-1),
        "stalker": L("Is on the shelf. The broom cannot reach the shelf.", intellect=2, agility=1),
        "purrsuader": L("Makes the sweeping stop by being adorable at it.", charm=3),
        "tyrant": L("Sits on the swept pile. Sweeping is now over.", charm=2, strength=1),
        "weaver": L("Weaves between the bristles and out the far side.", agility=3),
        "dinner": L("Screams until the broom is put down. It is put down.", charm=2, intellect=1),
        "alley": L("Knows the broom. Steps aside before it starts.", agility=1, intellect=2),
    },
    "🚿": {
        "pouncer": L("Attacks the water. The water wins immediately.", strength=1, agility=-1),
        "loaf": L("Sits in the spray for a moment, then walks off steaming.", strength=2, intellect=1),
        "chonk": L("Becomes half his size and twice as furious.", strength=1, charm=-1),
        "ricochet": L("Is dry, wet, and dry again inside two seconds.", agility=3),
        "ghost": L("Was gone the moment the tap squeaked.", agility=2, intellect=2),
        "gremlin": L("Bites the shower. Is now a wet gremlin.", agility=1, charm=-2),
        "barger": L("Works out the tap and turns the water off.", intellect=3),
        "stalker": L("Watches the shower from the highest dry surface.", intellect=2, agility=1),
        "purrsuader": L("Sits wet and pitiful until somebody fetches a towel.", charm=3),
        "tyrant": L("Regards being wet as a failure of the household.", charm=2, strength=-1),
        "weaver": L("Slips between the drops. Emerges almost dry.", agility=3),
        "dinner": L("Drinks from the shower rather than the bowl provided.", intellect=1, charm=1),
        "alley": L("Has been rained on for years. Shrugs it off.", strength=2, intellect=1),
    },
    "🔥": {
        "pouncer": L("Crouches at the fire, then thinks better of pouncing.", intellect=1, strength=1),
        "loaf": L("Sits as close to the fire as physics allows.", strength=2, intellect=1),
        "chonk": L("Blocks the fire entirely. Everyone else is cold now.", strength=2, charm=1),
        "ricochet": L("Runs past the fire twice for no clear reason.", agility=2, intellect=-1),
        "ghost": L("Sits just outside the firelight, watching everybody.", intellect=2, agility=1),
        "gremlin": L("Bats at the fire once and learns nothing.", agility=1, intellect=-2),
        "barger": L("Understands heat before touching it. Rare, and smug.", intellect=3),
        "stalker": L("Watches the fire from above, where the warm air goes.", intellect=2, agility=1),
        "purrsuader": L("Takes the best spot by the fire and keeps it.", charm=3),
        "tyrant": L("The fire was lit for her. Everyone else may share.", charm=2, strength=1),
        "weaver": L("Winds past the fire close enough to worry people.", agility=2, charm=1),
        "dinner": L("Sits by the fire and mentions that fires cook things.", charm=2, intellect=1),
        "alley": L("Fire means people. People mean food. Moves closer.", intellect=2, charm=1),
    },
    "💀": {
        "pouncer": L("Pounces the skull. It rolls. Now it is a game.", strength=1, agility=1),
        "loaf": L("Sits beside the skull companionably. No comment.", intellect=2),
        "chonk": L("Pushes the skull off the table and watches it go.", strength=2, charm=1),
        "ricochet": L("Sends the skull round the arena at speed.", agility=2, strength=1),
        "ghost": L("Immediate, unsettling kinship with the skull.", intellect=2, agility=1),
        "gremlin": L("Wears the skull. Refuses to explain the skull.", charm=2, strength=1),
        "barger": L("Examines the jaw hinge with genuine professional interest.", intellect=3),
        "stalker": L("Puts the skull on a shelf, facing the other cats.", intellect=2, charm=-1),
        "purrsuader": L("Poses with the skull until somebody feels something.", charm=2, intellect=1),
        "tyrant": L("Sits in the skull. It is a throne with a face.", charm=2, strength=1),
        "weaver": L("Threads through both eye sockets without slowing.", agility=3),
        "dinner": L("Checks the skull for meat. Finds none. Is let down.", charm=1, intellect=-1),
        "alley": L("Has seen a skull before. Has seen several.", strength=1, intellect=2),
    },
    "🎃": {
        "pouncer": L("Ambushes from inside the pumpkin. Nobody expected a cat.", strength=1, agility=2),
        "loaf": L("Two heavy round things, sitting quietly together.", strength=2, intellect=1),
        "chonk": L("Is briefly mistaken for the pumpkin and says nothing.", strength=2, charm=1),
        "ricochet": L("Rolls the pumpkin the length of the arena.", agility=2, strength=1),
        "ghost": L("Occupies the pumpkin. The pumpkin now has opinions.", agility=1, intellect=2),
        "gremlin": L("Hollows the pumpkin further, uninvited, at speed.", strength=2, agility=1),
        "barger": L("Gets in through the mouth to see how it was made.", intellect=2, strength=1),
        "stalker": L("Sits on the pumpkin and gains commanding height.", intellect=2, agility=1),
        "purrsuader": L("Sits behind the pumpkin and becomes a photograph.", charm=3),
        "tyrant": L("Uses the pumpkin as a plinth. She is a monument.", charm=2, strength=1),
        "weaver": L("In one eye of the pumpkin and out the other.", agility=3),
        "dinner": L("Assumes the pumpkin is a very large portion.", charm=2, strength=1),
        "alley": L("Sleeps in the pumpkin. It is warm and nobody wants it.", strength=1, charm=1),
    },
    "👑": {
        "pouncer": L("Knocks the crown off whoever is wearing it.", strength=1, agility=2),
        "loaf": L("Sits under the crown. It fits, in a manner of speaking.", strength=1, intellect=1),
        "chonk": L("The crown sits on his head like a bracelet.", strength=1, charm=2),
        "ricochet": L("Sends the crown skidding under the seating.", agility=2),
        "ghost": L("The crown is on a different cat now. Nobody saw.", agility=2, intellect=2),
        "gremlin": L("Wears the crown backwards and will not be corrected.", charm=2, intellect=-1),
        "barger": L("Works out the crown means nothing and ignores it.", intellect=2),
        "stalker": L("Takes the crown up high where it can be admired.", intellect=1, agility=2),
        "purrsuader": L("Is given the crown. Did not have to ask for it.", charm=3, intellect=1),
        "tyrant": L("Puts it on. Of course it fits. It was always hers.", charm=3, strength=1),
        "weaver": L("Winds through the crown and wears it as a collar.", agility=2, charm=2),
        "dinner": L("Tries to eat the crown, briefly, out of principle.", charm=1, intellect=-1),
        "alley": L("Regards the crown as tradeable. Which it is.", intellect=2, charm=1),
    },
    "💻": {
        "pouncer": L("Attacks the cursor on the screen from the side.", agility=2, intellect=-1),
        "loaf": L("Sits on the keyboard. It is warm and flat and his.", strength=2, intellect=1),
        "chonk": L("Lies across the whole laptop. It runs hotter now.", strength=2, agility=-1),
        "ricochet": L("Walks over the keys at speed. Something is sent.", agility=1, intellect=-2),
        "ghost": L("Sits behind the screen where the light cannot reach.", intellect=2, agility=1),
        "gremlin": L("Sends a message to somebody with one confident paw.", charm=2, intellect=-1),
        "barger": L("Presses keys until the machine does something new.", intellect=3),
        "stalker": L("Watches the screen from above, head tilted.", intellect=2),
        "purrsuader": L("Sits between the human and the laptop. Work stops.", charm=2, intellect=2),
        "tyrant": L("Occupies the laptop. Nobody is working today.", charm=2, strength=1),
        "weaver": L("Walks across the keyboard slowly, tail up, twice.", charm=2, agility=1),
        "dinner": L("Cries at the laptop user until the laptop is closed.", charm=3),
        "alley": L("Sleeps on the laptop purely for the warmth.", strength=1, intellect=1),
    },
    "🚪": {
        "pouncer": L("Waits behind the door for whatever comes through it.", strength=1, agility=2),
        "loaf": L("Sits precisely in the doorway. Nobody may pass.", strength=2, intellect=1),
        "chonk": L("Fills the doorway completely, without meaning to.", strength=2, agility=-1),
        "ricochet": L("Through the door, round the room, back out again.", agility=3),
        "ghost": L("Is on the other side of the door already.", agility=2, intellect=1),
        "gremlin": L("Yowls at the door, goes through, wants it opened again.", charm=1, intellect=-2),
        "barger": L("Finally. A door. He has waited his whole life.", intellect=3, strength=1),
        "stalker": L("Sits on top of the door, balanced, watching.", intellect=2, agility=2),
        "purrsuader": L("Waits by the door until a human opens it for her.", charm=3),
        "tyrant": L("Requires the door open. And then closed. And then open.", charm=2, strength=1),
        "weaver": L("Slips through the gap before the door is properly open.", agility=3),
        "dinner": L("Cries at the door because dinner might be behind it.", charm=2, intellect=-1),
        "alley": L("Checks the door is not a trap, then goes through.", intellect=2, agility=1),
    },
    "🌧️": {
        "pouncer": L("Pounces raindrops on the glass, one at a time.", agility=2, intellect=-1),
        "loaf": L("Sits by the window and is glad to be indoors.", strength=1, intellect=2),
        "chonk": L("Sees the rain and returns to bed immediately.", strength=1, agility=-1),
        "ricochet": L("Runs from window to window as the rain moves.", agility=2),
        "ghost": L("Sits in the dark watching the rain, unblinking.", intellect=2, agility=1),
        "gremlin": L("Screams at the rain. The rain continues.", charm=1, intellect=-1),
        "barger": L("Checks every door in case one leads to dry outside.", intellect=2, strength=1),
        "stalker": L("Watches the rain from the highest windowsill.", intellect=2),
        "purrsuader": L("Blames the rain on the nearest human, at length.", charm=2, intellect=1),
        "tyrant": L("Demands the rain be stopped. Is astonished it continues.", charm=2),
        "weaver": L("Winds round wet ankles by the door, delighted.", charm=2, agility=1),
        "dinner": L("Points out that rainy days are for extra dinners.", charm=2, intellect=1),
        "alley": L("Knows exactly which corner stays dry. Goes there.", intellect=2, strength=1),
    },
    "🪑": {
        "pouncer": L("Waits under the chair for ankles. Ankles arrive.", strength=1, agility=2),
        "loaf": L("Occupies the chair entirely. The chair is resolved.", strength=2, intellect=1),
        "chonk": L("Fits the chair the way water fits a glass.", strength=2, charm=1),
        "ricochet": L("Uses the chair as a launch pad, twice.", agility=3),
        "ghost": L("Is under the chair. Has been for some time.", agility=1, intellect=2),
        "gremlin": L("Shreds the side of the chair while watching you.", strength=2, charm=-1),
        "barger": L("Works out how to get the chair to the counter.", intellect=3),
        "stalker": L("Uses the chair to reach the thing above the chair.", intellect=2, agility=1),
        "purrsuader": L("Takes the warm chair the second it is vacated.", charm=2, intellect=2),
        "tyrant": L("The chair is a throne and always has been.", charm=3),
        "weaver": L("Figure-eights the chair legs without touching one.", agility=3),
        "dinner": L("Sits on the chair at the table and waits to be served.", charm=2, intellect=1),
        "alley": L("A chair is off the ground and off the ground is safe.", intellect=2, strength=1),
    },
    "💉": {
        "pouncer": L("Ambushes the vet's hand. It was always going to happen.", strength=2, charm=-1),
        "loaf": L("Accepts the injection without moving at all.", strength=2, intellect=1),
        "chonk": L("Becomes immovable. Three people are now involved.", strength=3, agility=-1),
        "ricochet": L("Is behind the radiator before the cap is off.", agility=3),
        "ghost": L("Cannot be found. The appointment is rescheduled.", agility=3, intellect=1),
        "gremlin": L("Bites the vet. Everyone saw it coming except the vet.", strength=1, charm=-2),
        "barger": L("Works out the carrier door and is halfway home.", intellect=3, agility=1),
        "stalker": L("Watches from the top of the cupboard. Will not come down.", intellect=2, agility=2),
        "purrsuader": L("Is so charming the vet apologises to her.", charm=3, intellect=1),
        "tyrant": L("Regards the whole appointment as a serious betrayal.", charm=2, strength=-1),
        "weaver": L("Winds round the vet's legs and is briefly forgotten.", agility=2, charm=1),
        "dinner": L("Screams as though starving. The vet is unmoved.", charm=2, intellect=-1),
        "alley": L("Has had worse from a fence. Sits through it.", strength=2, intellect=1),
    },
    "🥊": {
        "pouncer": L("Grabs the glove with both paws and kicks it.", strength=2, agility=1),
        "loaf": L("Sits on the glove. The fight is over, apparently.", strength=2, intellect=1),
        "chonk": L("Leans on the glove until it stops being upright.", strength=2, charm=1),
        "ricochet": L("Bounces off the glove and comes straight back.", agility=2, strength=1),
        "ghost": L("Hits the glove once from somewhere behind it.", agility=2, intellect=1),
        "gremlin": L("Attacks the glove with everything, at 3am energy.", strength=2, charm=-1),
        "barger": L("Works out the glove is padded and stops worrying.", intellect=2, strength=1),
        "stalker": L("Drops onto the glove from above without warning.", intellect=1, agility=2),
        "purrsuader": L("Bats the glove gently and is called brave.", charm=3),
        "tyrant": L("Sits on the glove. She does not need a glove.", charm=2, strength=1),
        "weaver": L("Winds round the glove until nobody can swing it.", agility=2, charm=1),
        "dinner": L("Checks whether the glove is food. It smells promising.", charm=1, intellect=-1),
        "alley": L("Has been in real fights. Regards the glove as soft.", strength=2, intellect=1),
    },
    "👖": {
        "loaf": L("Sits on them. They are warm now, and they are his.", strength=1, intellect=1),
        "pouncer": L("Waits inside one leg for eleven minutes. Something will walk past.", agility=2),
        "chonk": L("Gets into them. Gets stuck in them. Refuses all help.", strength=2, agility=-1),
        "ricochet": L("Wears them briefly at full speed, off three walls.", agility=2, strength=-1),
        "ghost": L("Is inside the trousers. Nobody saw it get in.", agility=1, intellect=1),
        "gremlin": L("Shreds them to threads in nine seconds and is delighted.", strength=2, charm=-1),
        "barger": L("Works out the pockets. Removes everything in them.", intellect=2),
        "stalker": L("Drags them onto the wardrobe. They live up there now.", intellect=1, agility=1),
        "purrsuader": L("Lies on them so you cannot leave the house.", intellect=2, charm=1),
        "tyrant": L("Sits on them while you are still wearing them.", charm=2, strength=1),
        "weaver": L("Winds through both legs and comes out fully dressed.", charm=2, agility=1),
        "dinner": L("Cries into the trousers until fed.", charm=2),
        "alley": L("Has slept in worse. Sleeps in these.", strength=1, charm=1),
    },
    "🕯️": {
        "loaf": L("Sits close. Is warm. Is slightly on fire. Unbothered.", strength=1, intellect=-1),
        "pouncer": L("Stalks the flame. The flame does not move. Confusing.", agility=1, intellect=-1),
        "chonk": L("Blocks all the light. Room goes dark.", strength=2),
        "ricochet": L("Knocks it over twice at speed. House survives.", agility=2, intellect=-2),
        "ghost": L("Is lit from below and looks appalling.", intellect=1, charm=-1),
        "gremlin": L("Bats the flame. Learns. Bats it again. Learns nothing.", agility=1, intellect=-2),
        "barger": L("Works out heat before touching it. Rare and smug.", intellect=3),
        "stalker": L("Watches from above, planning something with wax.", intellect=2),
        "purrsuader": L("Arranges herself in the candlelight. Devastating.", charm=3),
        "tyrant": L("Sits between you and the candle. Deal with it.", charm=2, strength=1),
        "weaver": L("Winds past it four times without singeing a hair.", agility=3),
        "dinner": L("Cries at a candle. It is not food. She insists.", charm=2, intellect=-1),
        "alley": L("Fire means people. People mean food. Approaches.", intellect=1, charm=1),
    },

    # --- the faces people actually send, in order of how often they send them ---
    "😄": {   # grinning face with smiling eyes, the most used emoji here
        "pouncer": L("Reads the grin as an opening and goes for the ankle.", strength=2),
        "loaf": L("Is smiled at. Does not smile back. Does not need to.", intellect=2),
        "chonk": L("Assumes the smile is admiration, which it usually is.", charm=2, strength=1),
        "ricochet": L("Takes the smile as a starting pistol and is gone.", agility=3),
        "ghost": L("Watches the smiling face without blinking. It stops smiling.", intellect=2),
        "gremlin": L("Grins back with too many teeth and everyone steps away.", charm=2, intellect=-1),
        "barger": L("Notes that smiling humans open tins. Follows the smile.", intellect=3),
        "stalker": L("Observes the smile from above, deciding whether it is genuine.", intellect=2),
        "purrsuader": L("Smiles back, in the way cats do, and wins the room.", charm=3, intellect=1),
        "tyrant": L("Accepts the smile as the tribute it clearly is.", charm=2),
        "weaver": L("Winds round the smiling one and is smiled at more.", charm=2, agility=1),
        "dinner": L("A smile means a good mood, and a good mood means snacks.", charm=3, intellect=1),
        "alley": L("Has learned that a smile is usually safe. Approaches.", intellect=2, charm=1),
    },
    "🙂": {   # slightly smiling face
        "pouncer": L("The small smile gives nothing away. Crouches anyway.", strength=1, agility=1),
        "loaf": L("A polite smile is met with a slow blink. Business concluded.", intellect=2),
        "chonk": L("Reads the tiny smile as approval of his size.", charm=2),
        "ricochet": L("Cannot read the small smile and runs off to think.", agility=2, intellect=-1),
        "ghost": L("Finds the small smile faintly threatening and respects it.", intellect=2, agility=1),
        "gremlin": L("Distrusts a smile that small. Bites something.", strength=1, intellect=-1),
        "barger": L("Studies the smile for what is behind it. Something is.", intellect=3),
        "stalker": L("Watches the polite smile and waits it out.", intellect=2),
        "purrsuader": L("Recognises a professional. Nods slightly.", intellect=2, charm=2),
        "tyrant": L("A small smile is insufficient. She waits for a better one.", charm=2),
        "weaver": L("Turns the small smile into a proper one in four seconds.", charm=3),
        "dinner": L("Takes the polite smile as a firm promise of food.", charm=2, intellect=-1),
        "alley": L("Knows a polite smile means neither food nor danger.", intellect=2),
    },
    "🤣": {   # rolling on the floor laughing
        "pouncer": L("Somebody is on the floor. Everything on the floor is fair game.", strength=2, agility=1),
        "loaf": L("Waits for the laughing to stop. It always stops.", intellect=2),
        "chonk": L("Climbs onto the laughing person. They laugh harder. Then less.", strength=2, charm=1),
        "ricochet": L("Joins in at speed without understanding the joke.", agility=2, intellect=-1),
        "ghost": L("Is unnerved by the laughing and watches from behind a leg.", agility=1, intellect=1),
        "gremlin": L("Laughing means chaos, and chaos is where it lives.", agility=2, charm=1),
        "barger": L("Uses the laughter as cover and gets into the cupboard.", intellect=3),
        "stalker": L("Observes the whole collapse from the bookshelf.", intellect=2),
        "purrsuader": L("Sits on the laughing chest. The laughing becomes wheezing.", charm=2, intellect=1),
        "tyrant": L("Does not care for being laughed near. Turns her back.", charm=2),
        "weaver": L("Winds round the person on the floor, thrilled by the new height.", charm=2, agility=1),
        "dinner": L("Cries over the laughter until somebody notices her instead.", charm=3),
        "alley": L("Loud humans usually mean dropped food. Moves closer.", intellect=2, charm=1),
    },
    "❤": {       # red heart
        "pouncer": L("Pounces the heart. Affection is a target like any other.", strength=1, agility=1),
        "loaf": L("Accepts the love without acknowledging that it happened.", strength=1, intellect=2),
        "chonk": L("Is loved, knows it, and lies down to receive more.", charm=3),
        "ricochet": L("Is loved for about a second, then is elsewhere.", agility=2, charm=1),
        "ghost": L("Is embarrassed by the heart and hides behind something.", agility=2, charm=-1),
        "gremlin": L("Bites the hand that loves it, gently, out of affection.", charm=1, strength=1),
        "barger": L("Works out that being loved gets doors opened.", intellect=3),
        "stalker": L("Watches the affection from above, wanting some.", intellect=2),
        "purrsuader": L("This is her currency and she is extremely rich.", charm=3, intellect=1),
        "tyrant": L("Naturally. Everyone loves her. Next.", charm=3),
        "weaver": L("Winds round every ankle present and collects all of it.", charm=3, agility=1),
        "dinner": L("Love is nice. Love with food attached would be nicer.", charm=2, intellect=1),
        "alley": L("Takes the affection carefully, still half expecting a trick.", charm=2, intellect=1),
    },
    "😅": {   # grinning face with sweat
        "pouncer": L("Senses nerves and picks that one to jump on.", strength=2, agility=1),
        "loaf": L("Somebody is anxious. The Loaf is not. The Loaf sits.", intellect=2, strength=1),
        "chonk": L("Sits on the nervous one until they calm down. It works.", strength=2, charm=1),
        "ricochet": L("Catches the nervous energy and doubles it.", agility=2, intellect=-1),
        "ghost": L("Notices the sweat. Files it. Says nothing.", intellect=2),
        "gremlin": L("Makes the nervous situation considerably worse.", charm=1, intellect=-1),
        "barger": L("Nervous people forget to shut doors. Waits.", intellect=3),
        "stalker": L("Watches the nervous one from above, which does not help.", intellect=2),
        "purrsuader": L("Comforts the nervous one and is fed for it.", charm=3, intellect=1),
        "tyrant": L("Nerves are unbecoming. She looks away.", charm=2),
        "weaver": L("Winds figure eights until the nervous one laughs.", charm=2, agility=1),
        "dinner": L("Uses the nervousness as leverage for an early dinner.", charm=2, intellect=2),
        "alley": L("Reads the nerves correctly and keeps one exit in view.", intellect=2, agility=1),
    },
    "😂": {   # face with tears of joy
        "pouncer": L("Attacks the shaking shoulders from behind.", strength=1, agility=2),
        "loaf": L("Regards the crying-laughing human with deep suspicion.", intellect=2),
        "chonk": L("Assumes he caused this. He is usually right.", charm=2, strength=1),
        "ricochet": L("Runs a lap because something is clearly happening.", agility=2),
        "ghost": L("Cannot tell if this is crying and quietly withdraws.", agility=1, intellect=1),
        "gremlin": L("Adds to the noise until nobody can hear anything.", charm=2, intellect=-1),
        "barger": L("Notes that nobody is watching the fridge right now.", intellect=3),
        "stalker": L("Watches the whole performance without expression.", intellect=2),
        "purrsuader": L("Arrives to be comforting, and is thanked for it.", charm=3),
        "tyrant": L("Waits, with visible patience, for this to be over.", charm=2),
        "weaver": L("Winds round the shaking legs, delighted by the wobbling.", agility=2, charm=1),
        "dinner": L("Cries harder than the human, and about food.", charm=3, intellect=-1),
        "alley": L("Cannot tell laughing from crying, and stays back a little.", intellect=1, agility=1),
    },
    "👀": {   # eyes
        "pouncer": L("Being watched changes nothing. Pounces anyway.", strength=2),
        "loaf": L("Meets the stare. Wins the staring contest by sitting.", intellect=2, strength=1),
        "chonk": L("Is being looked at, and gives them something to look at.", charm=2),
        "ricochet": L("Cannot be watched for long. Leaves the eyeline at speed.", agility=3),
        "ghost": L("Being seen is the one thing it cannot stand. Slips behind something.", agility=2, charm=-1),
        "gremlin": L("Holds eye contact and knocks something over.", charm=2, intellect=-1),
        "barger": L("Waits, watching the watcher, until the watcher blinks.", intellect=3),
        "stalker": L("Has been watching them for some time already.", intellect=3),
        "purrsuader": L("Slow blinks at the eyes. The eyes soften immediately.", charm=3, intellect=1),
        "tyrant": L("Of course they are looking. She is the best thing here.", charm=3),
        "weaver": L("Breaks the stare by walking directly through it.", agility=2, charm=1),
        "dinner": L("Stares back, hard, at the person nearest the food.", charm=2, intellect=1),
        "alley": L("Does not like being stared at. Angles away from the eyes.", agility=1, intellect=2),
    },
    "🤔": {   # thinking face
        "pouncer": L("Waits for the thinking to end so something can happen.", strength=1),
        "loaf": L("Thinks too, in his way, and it looks identical to sleeping.", intellect=3),
        "chonk": L("Thinking is a good time to get into the food cupboard.", strength=1, charm=1),
        "ricochet": L("Has no time for thinking and knocks something over.", agility=2, intellect=-1),
        "ghost": L("Thinks along, silently, and reaches the answer first.", intellect=3),
        "gremlin": L("Interrupts the thinking by sitting on the thinker.", charm=2, intellect=-1),
        "barger": L("Recognises the face of somebody working out a problem.", intellect=3, strength=1),
        "stalker": L("Watches them think, and thinks about them thinking.", intellect=3),
        "purrsuader": L("Puts one paw on the thinker. The thinking stops.", charm=2, intellect=2),
        "tyrant": L("Whatever is being considered, the answer concerns her.", charm=2),
        "weaver": L("Winds round the thinker until the thought is lost.", agility=2, charm=1),
        "dinner": L("Hopes very hard that the thought is about dinner.", charm=2),
        "alley": L("Waits out the thinking. Decisions usually mean movement.", intellect=2),
    },
    "😭": {   # loudly crying face
        "pouncer": L("Stops. Even a Pouncer knows when not to pounce.", intellect=2),
        "loaf": L("Sits against the crying one, heavily, and stays there.", strength=2, charm=1),
        "chonk": L("Puts his considerable weight on their lap. It helps.", charm=3, strength=1),
        "ricochet": L("Slows down for once and sits nearby, fidgeting.", charm=1, agility=-1),
        "ghost": L("Comes out from wherever it was, which it never does.", charm=2, intellect=1),
        "gremlin": L("Brings the crying one a bottle cap. It is what it has.", charm=2),
        "barger": L("Opens the door and sits in it, keeping watch.", intellect=2, charm=1),
        "stalker": L("Comes down off the shelf. That is significant.", charm=2, intellect=1),
        "purrsuader": L("Knows exactly what to do here, and does it.", charm=3, intellect=1),
        "tyrant": L("Permits lengthy holding. This is an enormous concession.", charm=3),
        "weaver": L("Presses her whole side against the crying one's leg.", charm=3),
        "dinner": L("Stops asking for food. Sits down and leans in.", charm=3, intellect=1),
        "alley": L("Has seen people cry before. Sits close and says nothing.", charm=2, intellect=2),
    },
    "👍": {   # thumbs up
        "pouncer": L("Grabs the raised thumb with both paws.", strength=1, agility=2),
        "loaf": L("Accepts the approval without moving to collect it.", intellect=2),
        "chonk": L("Approval. Excellent. Lies down to enjoy it properly.", charm=2, strength=1),
        "ricochet": L("Takes the thumbs up as permission and is gone.", agility=3),
        "ghost": L("Is approved of, which it finds mildly suspicious.", intellect=2),
        "gremlin": L("Bites the approving thumb. It meant well.", strength=1, charm=-1),
        "barger": L("A raised thumb is not a tin opener. Loses interest.", intellect=2),
        "stalker": L("Notes the approval from above and files it away.", intellect=2),
        "purrsuader": L("Has been approved of, and immediately asks for more.", charm=3),
        "tyrant": L("Correct. She was always going to be approved of.", charm=3),
        "weaver": L("Rubs her face on the thumb and claims it entirely.", charm=2, agility=1),
        "dinner": L("Approval is not food. Points this out at volume.", charm=2, intellect=-1),
        "alley": L("Reads the gesture as friendly and relaxes one notch.", intellect=2, charm=1),
    },
    "🥺": {   # pleading face
        "pouncer": L("Is unmoved. Pounces the pleading one anyway.", strength=2, charm=-1),
        "loaf": L("Is begged at. Continues to sit. Nothing changes.", intellect=2, strength=1),
        "chonk": L("Falls for it completely and shares his food.", charm=2, strength=-1),
        "ricochet": L("Cannot hold still long enough to be begged at.", agility=2),
        "ghost": L("Recognises begging as a technique and notes it down.", intellect=2),
        "gremlin": L("Copies the face, badly, to get the same result.", charm=2, intellect=-1),
        "barger": L("Prefers to open the cupboard than to ask for it.", intellect=3),
        "stalker": L("Observes the begging with quiet professional interest.", intellect=2),
        "purrsuader": L("Watches an amateur at work and is faintly insulted.", charm=2, intellect=2),
        "tyrant": L("Does not beg. Has never begged. Will not start now.", charm=3),
        "weaver": L("Adds ankle winding to the begging. It works better.", charm=3, agility=1),
        "dinner": L("This is her native language and she is fluent.", charm=3, intellect=1),
        "alley": L("Has begged for real. Finds this version a bit much.", intellect=2, charm=1),
    },
    "🤡": {   # clown face
        "pouncer": L("Something with a red nose. Removes the red nose.", strength=2, agility=1),
        "loaf": L("Is not entertained. Was not going to be entertained.", intellect=2),
        "chonk": L("Finds the clown delightful and demands more clown.", charm=2),
        "ricochet": L("Runs from the clown, then back to it, then away.", agility=2, intellect=-1),
        "ghost": L("Does not care for the clown at all and goes very still.", agility=1, intellect=1),
        "gremlin": L("Recognises a colleague and joins the act.", charm=2, agility=1),
        "barger": L("Works out the clown is a person in paint. Relaxes.", intellect=3),
        "stalker": L("Watches the clown from the highest available point.", intellect=2, agility=1),
        "purrsuader": L("Upstages the clown without appearing to try.", charm=3, intellect=1),
        "tyrant": L("Will not share attention with a clown. Leaves the ring.", charm=2),
        "weaver": L("Trips the clown, which improves the act enormously.", agility=2, charm=2),
        "dinner": L("Asks the clown for food. Clowns have pockets.", charm=2, intellect=1),
        "alley": L("Has met street performers. Keeps a professional distance.", intellect=2),
    },
    "😛": {
        "pouncer": L("A tongue is out. The tongue is now a target.", strength=2, agility=1),
        "loaf": L("Is being teased. Blinks once, very slowly, and wins.", intellect=2),
        "chonk": L("Sticks his own tongue out and forgets to put it away.", charm=2, intellect=-1),
        "ricochet": L("Sees the tongue, boops it, and is three rooms away.", agility=3),
        "ghost": L("Files the rudeness away for use at a better time.", intellect=2),
        "gremlin": L("Escalates immediately. Two tongues out. Nobody wins.", charm=2, intellect=-1),
        "barger": L("Ignores the tongue. Tongues do not open doors.", intellect=2),
        "stalker": L("Watches the tongue from above, unimpressed by all of it.", intellect=2),
        "purrsuader": L("Finds the teasing charming and doubles her rate of purring.", charm=3),
        "tyrant": L("Being teased is beneath her. She turns her whole back.", charm=2),
        "weaver": L("Winds round the teaser until the teasing turns to fussing.", charm=2, agility=1),
        "dinner": L("A tongue means food was recently eaten. Investigates.", charm=2, intellect=1),
        "alley": L("Reads the teasing as friendly, which it is.", intellect=2, charm=1),
    },
    "😦": {
        "pouncer": L("Something startled them. Uses the confusion to get closer.", agility=2),
        "loaf": L("Whatever the matter is, it is not a matter for a Loaf.", intellect=2, strength=1),
        "chonk": L("Assumes the shock is about how much cat there is.", charm=2),
        "ricochet": L("Panics on principle and knocks two things over.", agility=2, intellect=-1),
        "ghost": L("Was the reason for the shock. Nobody saw it arrive.", agility=2, intellect=2),
        "gremlin": L("Is delighted. This is the face it works for.", charm=2, agility=1),
        "barger": L("Checks what they are looking at. It is worth checking.", intellect=3),
        "stalker": L("Already knows what they have only just noticed.", intellect=3),
        "purrsuader": L("Arrives to be reassuring and is held for ten minutes.", charm=3),
        "tyrant": L("Waits for somebody to explain the disturbance to her.", charm=2),
        "weaver": L("Winds round the shocked one until they are steadier.", charm=2, agility=1),
        "dinner": L("Shock means a dropped plate. Moves toward the plate.", charm=2, intellect=1),
        "alley": L("A face like that means trouble. Checks both exits.", intellect=2, agility=1),
    },
    "😆": {
        "pouncer": L("Eyes are shut. This is the ideal moment to pounce.", strength=2, agility=2),
        "loaf": L("Waits for the laughing to finish. It takes a while.", intellect=2),
        "chonk": L("Laughs along in the only way a Chonk can, by wobbling.", charm=2),
        "ricochet": L("Takes the laugh as a signal and runs a full circuit.", agility=2),
        "ghost": L("Moves while everyone's eyes are closed. Of course it does.", agility=3),
        "gremlin": L("Was the cause of the laughing and intends to be again.", charm=2, agility=1),
        "barger": L("Squeezed-shut eyes mean nobody is guarding the counter.", intellect=3),
        "stalker": L("Watches from above and does not join in with any of it.", intellect=2),
        "purrsuader": L("Sits in the middle of the laughter and collects the credit.", charm=3),
        "tyrant": L("Assumes she is being laughed at, and freezes the room.", charm=2, strength=1),
        "weaver": L("Weaves through the laughing group, brushing every leg.", agility=2, charm=1),
        "dinner": L("Laughter is a good mood, and good moods buy snacks.", charm=2, intellect=1),
        "alley": L("Loud, but the good kind of loud. Stays where it is.", intellect=2),
    },
    "😉": {
        "pouncer": L("Reads the wink as a signal and goes immediately.", strength=1, agility=2),
        "loaf": L("Is winked at. Closes both eyes, which is more effort.", intellect=2),
        "chonk": L("Winks back with his whole face. It is not a wink.", charm=2, intellect=-1),
        "ricochet": L("Misses the wink entirely. Was moving at the time.", agility=2, intellect=-1),
        "ghost": L("Understands the wink exactly and acts on it.", intellect=2, agility=1),
        "gremlin": L("Takes the wink as permission for absolutely anything.", agility=2, intellect=-1),
        "barger": L("A wink means a plan. Waits to find out whose.", intellect=3),
        "stalker": L("Sees who the wink was really aimed at.", intellect=3),
        "purrsuader": L("Slow blinks back, which is the cat version and better.", charm=3, intellect=1),
        "tyrant": L("Accepts the wink as the correct level of deference.", charm=2),
        "weaver": L("Winds round the winker and gets let in on it.", charm=2, agility=1),
        "dinner": L("Decides the wink was about food. Follows the winker.", charm=2, intellect=1),
        "alley": L("Knows a wink means an arrangement, and wants a share.", intellect=2, charm=1),
    },
    "😁": {
        "pouncer": L("All those teeth are showing. Goes for a paw instead.", strength=1, agility=1),
        "loaf": L("A wide grin earns one blink and nothing further.", intellect=2),
        "chonk": L("Beams back, which mostly involves squashing his own face.", charm=3),
        "ricochet": L("Is off before the grin has finished forming.", agility=3),
        "ghost": L("Finds that many teeth unsettling and moves behind a chair.", agility=1, intellect=1),
        "gremlin": L("Grins wider. It becomes a competition. It gets strange.", charm=2, intellect=-1),
        "barger": L("Grinning people are distracted people. Tries the cupboard.", intellect=3),
        "stalker": L("Observes the grin, unblinking, until it falters.", intellect=2),
        "purrsuader": L("Returns the grin in cat, and is immediately adored.", charm=3),
        "tyrant": L("Approves of the grin. Approval is all she offers.", charm=2),
        "weaver": L("Winds round the grinning one and collects the good mood.", charm=2, agility=1),
        "dinner": L("A grin is close enough to a promise of dinner.", charm=2, intellect=1),
        "alley": L("Reads the grin as safe and comes a step closer.", intellect=2, charm=1),
    },
    "🤷": {
        "pouncer": L("The raised hands are up. Goes for the ankles instead.", strength=1, agility=2),
        "loaf": L("Shrugging is the human version of what he does all day.", intellect=3),
        "chonk": L("Cannot shrug. Has no shoulders to speak of. Wobbles.", charm=2, agility=-1),
        "ricochet": L("Does not wait to find out what nobody knows.", agility=2),
        "ghost": L("Knows the answer, and is not going to give it.", intellect=3),
        "gremlin": L("Nobody knows anything, so nothing is its fault.", charm=2, intellect=-1),
        "barger": L("Nobody knows how it works, so he will find out himself.", intellect=3, strength=1),
        "stalker": L("Watched the whole thing happen. Says nothing about it.", intellect=3),
        "purrsuader": L("Takes advantage of the confusion to be fed twice.", charm=2, intellect=2),
        "tyrant": L("Finds not knowing unacceptable in her staff.", charm=2),
        "weaver": L("Winds round the shrugging one until they decide something.", charm=2, agility=1),
        "dinner": L("Nobody knows if she has been fed. She has. Insists otherwise.", charm=3, intellect=1),
        "alley": L("Shrugs back, in the way of a cat that has seen worse.", intellect=2, charm=1),
    },
    "😮": {
        "pouncer": L("An open mouth is an opening. Goes.", strength=2, agility=1),
        "loaf": L("Whatever the surprise is, it can be dealt with sitting down.", intellect=2),
        "chonk": L("Is the surprise. Has knocked something enormous over.", strength=2, charm=1),
        "ricochet": L("Caused the gasp and is already somewhere else.", agility=3),
        "ghost": L("Appeared right beside them. That is the whole trick.", agility=2, intellect=2),
        "gremlin": L("Gasps too, at nothing, because it looked fun.", charm=2, intellect=-1),
        "barger": L("Follows the gasp to see what has been discovered.", intellect=3),
        "stalker": L("Saw it coming from the shelf a good minute ago.", intellect=3),
        "purrsuader": L("Uses the moment of surprise to get onto the good chair.", charm=2, intellect=2),
        "tyrant": L("Assumes the gasp is about her arrival, and holds the pose.", charm=3),
        "weaver": L("Weaves through everyone's legs while they are all staring.", agility=3),
        "dinner": L("An open mouth means eating. Comes to check.", charm=2, intellect=1),
        "alley": L("A sudden gasp means something changed. Moves to the wall.", agility=2, intellect=1),
    },
    "😊": {
        "pouncer": L("Kindness lowers a guard, and a lowered guard is an opening.", strength=1, agility=1),
        "loaf": L("Warm smile, warm room, warm loaf. Everything is correct.", strength=1, intellect=2),
        "chonk": L("Is smiled at fondly and rolls over to be admired.", charm=3),
        "ricochet": L("Accepts the kindness at speed, in passing.", agility=2, charm=1),
        "ghost": L("Comes half a step closer, which for a Ghost is enormous.", charm=2, intellect=1),
        "gremlin": L("Is kind back, briefly, and is embarrassed about it.", charm=2),
        "barger": L("Kind people are the ones who open doors on request.", intellect=3),
        "stalker": L("Comes down one shelf. Only one.", intellect=1, charm=2),
        "purrsuader": L("Recognises real warmth and settles in for the evening.", charm=3, intellect=1),
        "tyrant": L("Accepts the fondness as her due, and permits stroking.", charm=3),
        "weaver": L("Winds round the kind one and stays wound.", charm=3, agility=1),
        "dinner": L("Kind faces feed cats. This is simply true.", charm=3, intellect=1),
        "alley": L("Trusts the kind face a little, and that is a lot.", charm=2, intellect=2),
    },
    "😑": {
        "pouncer": L("Nothing in that face says no. Pounces.", strength=2),
        "loaf": L("Two blank expressions, holding steady. Nobody blinks.", intellect=3),
        "chonk": L("Cannot tell if he is in trouble. Eats anyway.", strength=1, intellect=-1),
        "ricochet": L("Reads the flat face correctly and leaves at speed.", agility=2, intellect=1),
        "ghost": L("Recognises the face of somebody hiding something.", intellect=3),
        "gremlin": L("Knows exactly what it did. Does it again.", charm=1, intellect=-1),
        "barger": L("A blank face means no is coming. Acts before it does.", intellect=3, agility=1),
        "stalker": L("Matches the expression exactly, from the shelf.", intellect=3),
        "purrsuader": L("Purrs at the flat face until it cracks. It cracks.", charm=3, intellect=1),
        "tyrant": L("Finds the lack of enthusiasm frankly disrespectful.", charm=2),
        "weaver": L("Winds until the blank face gives up and looks down.", charm=2, agility=1),
        "dinner": L("A flat face means no extra dinner. Appeals the decision.", charm=2),
        "alley": L("A face with nothing in it is a face to watch.", intellect=2, agility=1),
    },
    "⚠": {
        "pouncer": L("A warning is just a thing to jump at from behind.", strength=2, intellect=-1),
        "loaf": L("Reads the warning. Considers it. Remains seated.", intellect=2, strength=1),
        "chonk": L("Cannot read, and is currently sitting on the sign.", strength=2, intellect=-1),
        "ricochet": L("Goes past the warning sign at full speed. Twice.", agility=2, intellect=-2),
        "ghost": L("Is already past the warning and has been for ten minutes.", agility=2, intellect=1),
        "gremlin": L("Treats the warning as an invitation, which for it, it is.", agility=2, intellect=-1),
        "barger": L("Understands the warning, and understands the way around it.", intellect=3),
        "stalker": L("Notes the warning from a safe height and stays there.", intellect=3),
        "purrsuader": L("Gets a human to deal with whatever the sign is about.", charm=2, intellect=2),
        "tyrant": L("Warnings are for other cats. She proceeds.", charm=2, strength=1),
        "weaver": L("Winds round the sign twice and knocks it flat.", agility=2, charm=1),
        "dinner": L("Warnings do not apply to a cat who has not been fed.", charm=2, intellect=-1),
        "alley": L("Has learned what warnings mean the hard way. Detours.", intellect=3),
    },
    "✅": {
        "pouncer": L("Permission granted. Uses it immediately and fully.", strength=2, agility=1),
        "loaf": L("Approval received. No action will be taken.", intellect=2),
        "chonk": L("Takes the tick as clearance to eat the whole bowl.", strength=2, charm=1),
        "ricochet": L("Is through the door before the tick finishes.", agility=3),
        "ghost": L("Had already done it before permission was given.", agility=2, intellect=2),
        "gremlin": L("Reads the tick as applying to everything, forever.", charm=2, intellect=-1),
        "barger": L("Did not need the permission but appreciates the confirmation.", intellect=3),
        "stalker": L("Waits anyway. Permission is not the same as a clear run.", intellect=3),
        "purrsuader": L("Was always going to get the yes. Collects it graciously.", charm=3),
        "tyrant": L("Correct. Approval was the only possible outcome.", charm=3),
        "weaver": L("Takes the yes and winds round the legs that gave it.", charm=2, agility=1),
        "dinner": L("A tick means dinner is agreed. Goes to the bowl at once.", charm=3, intellect=1),
        "alley": L("Waits a second to check the yes is real, then moves.", intellect=2, agility=1),
    },
    "🥳": {
        "pouncer": L("Party hats have strings. Strings are for pouncing.", strength=1, agility=2),
        "loaf": L("Sits through the entire party without changing position.", intellect=2, strength=1),
        "chonk": L("Eats something off the party table and is very happy.", strength=2, charm=1),
        "ricochet": L("Is the reason three drinks have gone over.", agility=2, intellect=-1),
        "ghost": L("Watches the party from under the sofa, unseen.", agility=2, intellect=1),
        "gremlin": L("Is wearing the party hat. Nobody put it there.", charm=3, intellect=-1),
        "barger": L("Parties mean open doors and unattended food.", intellect=3, strength=1),
        "stalker": L("Supervises the party from the top of the shelves.", intellect=2, agility=1),
        "purrsuader": L("Is the guest of honour by the second hour.", charm=3, intellect=1),
        "tyrant": L("The party is for her. She has always known this.", charm=3),
        "weaver": L("Weaves through every guest and is fussed by all of them.", charm=3, agility=1),
        "dinner": L("Parties have buffets. Positions herself accordingly.", charm=2, intellect=2),
        "alley": L("Crowds mean dropped food, and dropped food is dinner.", intellect=2, strength=1),
    },
    "😏": {
        "pouncer": L("That smirk means a plan. Pounces before it happens.", strength=2, agility=1),
        "loaf": L("Is smirked at. Remains a loaf. The smirk fades first.", intellect=3),
        "chonk": L("Does not follow the joke but is content to be included.", charm=2),
        "ricochet": L("Misses the smirk. Was in another room by then.", agility=2, intellect=-1),
        "ghost": L("Smirks back, which is much worse.", intellect=2, agility=1),
        "gremlin": L("Recognises the smirk of somebody about to do something.", charm=2, agility=1),
        "barger": L("Knows a smirk means a trick, and checks the door first.", intellect=3),
        "stalker": L("Has been watching long enough to know what the smirk is about.", intellect=3),
        "purrsuader": L("Smirks better. It is not a competition, but she wins it.", charm=3, intellect=1),
        "tyrant": L("Does not care to be smirked at. The audience is dismissed.", charm=2),
        "weaver": L("Winds round the smirker until the smirk becomes a laugh.", charm=2, agility=1),
        "dinner": L("A smirk means somebody is hiding food. Investigates.", charm=2, intellect=1),
        "alley": L("Trusts a smirk about as far as it can throw one.", intellect=2, agility=1),
    },
    "🤨": {
        "pouncer": L("Being doubted has never stopped a Pouncer.", strength=2),
        "loaf": L("Is questioned. Offers nothing. The eyebrow lowers first.", intellect=3),
        "chonk": L("Is caught. Has crumbs on his face. Denies everything.", strength=1, charm=1),
        "ricochet": L("Leaves before the question is finished.", agility=3),
        "ghost": L("Is the reason for the eyebrow, and remains unproven.", agility=2, intellect=2),
        "gremlin": L("Did it. Everyone knows it did it. It looks delighted.", charm=2, intellect=-1),
        "barger": L("Meets the raised eyebrow with total confidence.", intellect=3),
        "stalker": L("Raises nothing. Watches. Waits for the eyebrow to drop.", intellect=3),
        "purrsuader": L("Purrs until the suspicion becomes an apology.", charm=3, intellect=1),
        "tyrant": L("Being doubted is an outrage. She is above suspicion.", charm=2, strength=1),
        "weaver": L("Winds round the doubter's legs and is forgiven.", charm=3, agility=1),
        "dinner": L("Insists, in the face of evidence, that she is unfed.", charm=2, intellect=1),
        "alley": L("Knows that look. Has had that look aimed at it before.", intellect=2, agility=1),
    },
    "🙃": {
        "pouncer": L("Everything is upside down, which is a fine time to attack.", strength=1, agility=2),
        "loaf": L("Rolls onto his back and is now an upside-down loaf.", strength=2, charm=1),
        "chonk": L("Shows his belly. It is a trap. It is always a trap.", strength=2, charm=2),
        "ricochet": L("Is briefly upside down mid air and lands fine.", agility=3),
        "ghost": L("Hangs off the back of the sofa, watching from underneath.", agility=2, intellect=1),
        "gremlin": L("Is upside down and screaming, delightedly, for no reason.", agility=2, charm=1),
        "barger": L("Works out that the world is fine and the face is not.", intellect=3),
        "stalker": L("Watches upside down from the top of the door frame.", intellect=2, agility=2),
        "purrsuader": L("Rolls over precisely where somebody will see her do it.", charm=3),
        "tyrant": L("Permits belly viewing. Does not permit belly touching.", charm=3, strength=1),
        "weaver": L("Winds round ankles while upside down. Somehow works.", agility=3, charm=1),
        "dinner": L("Upside down and complaining, which carries further.", charm=2),
        "alley": L("Only goes upside down where it feels entirely safe.", charm=2, intellect=2),
    },
    "😋": {
        "pouncer": L("Somebody has eaten. There will be a plate. Goes to it.", strength=1, agility=2),
        "loaf": L("Licks his own lips in sympathy and settles further.", strength=2, intellect=1),
        "chonk": L("Has also just eaten, and is ready to eat again.", strength=3, agility=-1),
        "ricochet": L("Licks the plate and is gone before it is noticed.", agility=3),
        "ghost": L("The plate is clean. Nobody saw the plate get clean.", agility=2, intellect=1),
        "gremlin": L("Licks something that was not food and regrets nothing.", charm=1, intellect=-1),
        "barger": L("Traces the smell to the cupboard it came from.", intellect=3, strength=1),
        "stalker": L("Watches the eating from above, taking notes on portions.", intellect=2),
        "purrsuader": L("Sits by the plate looking as though she has never eaten.", charm=3, intellect=1),
        "tyrant": L("Expects the remainder of that to be brought to her.", charm=3),
        "weaver": L("Winds round the eater until something is dropped.", charm=2, agility=2),
        "dinner": L("Somebody has eaten and she has not. This is a crisis.", charm=3, intellect=1),
        "alley": L("Finds the smell first and follows it without hurrying.", intellect=2, strength=1),
    },
    "🙈": {
        "pouncer": L("Their eyes are covered. This is the best news all day.", strength=2, agility=2),
        "loaf": L("Puts a paw over his own face and goes back to sleep.", strength=1, intellect=2),
        "chonk": L("Hides by putting his face in a corner. The rest remains.", strength=1, charm=2),
        "ricochet": L("Cannot bear to watch and runs a lap instead.", agility=2),
        "ghost": L("Does not need to cover its eyes. Nobody can see it anyway.", agility=2, intellect=2),
        "gremlin": L("Covers its eyes and keeps doing the thing regardless.", charm=2, intellect=-1),
        "barger": L("Understands that covered eyes mean an unguarded room.", intellect=3),
        "stalker": L("Watches everything. Has never once looked away.", intellect=3),
        "purrsuader": L("Peeks between her paws to check she is still being watched.", charm=3),
        "tyrant": L("Refuses to look at something she disapproves of.", charm=2),
        "weaver": L("Winds round the legs of somebody who cannot see her coming.", agility=2, charm=1),
        "dinner": L("Cannot watch, but can still hear a tin. Comes running.", charm=2, intellect=1),
        "alley": L("Never covers its eyes. That is how things go wrong.", intellect=2, agility=1),
    },
    "🤦": {
        "pouncer": L("A hand has come up to a face. Pounces the hand.", strength=1, agility=2),
        "loaf": L("Whatever went wrong, it did not involve getting up.", intellect=2, strength=1),
        "chonk": L("Is the reason for the face palm and does not know it.", strength=2, charm=1),
        "ricochet": L("Is definitely the reason. Is already elsewhere.", agility=3, intellect=-1),
        "ghost": L("Watches the despair from the dark with mild interest.", intellect=2),
        "gremlin": L("Is delighted to have caused a whole hand-to-face moment.", charm=2, intellect=-1),
        "barger": L("Uses the moment of despair to get the cupboard open.", intellect=3),
        "stalker": L("Saw exactly how this went wrong and said nothing.", intellect=3),
        "purrsuader": L("Comforts the despairing one and is fed for the trouble.", charm=3, intellect=1),
        "tyrant": L("Nothing she has done warrants that face. Nothing ever does.", charm=2),
        "weaver": L("Winds round the shins until the hand comes off the face.", charm=3, agility=1),
        "dinner": L("Chooses this exact moment to ask about dinner.", charm=2, intellect=1),
        "alley": L("Recognises a person at the end of their patience. Waits.", intellect=3),
    },
    "💪": {
        "pouncer": L("A tensed arm is a branch, and branches are for climbing.", strength=2, agility=1),
        "loaf": L("Is heavier than that arm and has proved it before.", strength=3),
        "chonk": L("Flexes back. It is mostly fur but the spirit is right.", strength=2, charm=2),
        "ricochet": L("Runs up the arm and off the shoulder without stopping.", agility=3),
        "ghost": L("Is not impressed by strength and never has been.", intellect=2, agility=1),
        "gremlin": L("Attacks the flexed arm with everything it has.", strength=2, charm=-1),
        "barger": L("Notes that strong arms open the stiff cupboard door.", intellect=3, strength=1),
        "stalker": L("Watches from above, unmoved by displays of any kind.", intellect=2),
        "purrsuader": L("Sits on the flexed arm until it stops being flexed.", charm=2, intellect=2),
        "tyrant": L("Approves. That arm may carry her about the house.", charm=2, strength=1),
        "weaver": L("Winds round the arm and hangs off it, delighted.", agility=2, charm=2),
        "dinner": L("Strong arms carry heavy bowls. Follows the arm.", charm=2, intellect=1),
        "alley": L("Sizes up the arm, decides it is friendly, relaxes.", intellect=2, strength=1),
    },
    "🥰": {
        "pouncer": L("Too much affection. Escapes by pouncing something else.", agility=2),
        "loaf": L("Is adored at length. Permits every second of it.", strength=1, charm=2),
        "chonk": L("Melts. Becomes a puddle of extremely pleased cat.", charm=3, agility=-1),
        "ricochet": L("Accepts three seconds of adoration and leaves.", agility=2, charm=1),
        "ghost": L("Is overwhelmed by open affection and hides, pleased.", charm=2, agility=1),
        "gremlin": L("Purrs, then bites, then purrs. Nobody is safe.", charm=2, strength=1),
        "barger": L("Recognises adoration as the key to every door.", intellect=3, charm=1),
        "stalker": L("Comes down two whole shelves for this.", charm=2, intellect=1),
        "purrsuader": L("This is what she was built for. Absolutely radiant.", charm=3, intellect=1),
        "tyrant": L("Accepts adoration as routine. It is routine.", charm=3),
        "weaver": L("Winds round every leg in the room, collecting all of it.", charm=3, agility=1),
        "dinner": L("Being adored is close to being fed. Pushes for the rest.", charm=3, intellect=1),
        "alley": L("Takes the love slowly, the way you take a warm room.", charm=2, intellect=2),
    },
    "🎉": {
        "pouncer": L("Something exploded and there is paper everywhere. Perfect.", strength=1, agility=2),
        "loaf": L("A bang. Ears go back. Nothing else moves at all.", strength=2, intellect=1),
        "chonk": L("Is briefly airborne, which has not happened in years.", agility=2, strength=-1),
        "ricochet": L("Is at ceiling height before the paper has landed.", agility=3, intellect=-1),
        "ghost": L("Was gone before the popper was even picked up.", agility=3),
        "gremlin": L("Attacks the streamers and wears most of them.", agility=2, charm=1),
        "barger": L("Investigates the popper to understand what made the noise.", intellect=3),
        "stalker": L("Is already on the wardrobe. Was expecting this.", intellect=2, agility=2),
        "purrsuader": L("Is startled beautifully and is comforted at once.", charm=3),
        "tyrant": L("Regards the noise as an assault on her person.", charm=2, strength=-1),
        "weaver": L("Winds through the fallen streamers, tangling all of them.", agility=2, charm=1),
        "dinner": L("A party popper means a party means food. Follows.", charm=2, intellect=1),
        "alley": L("Bangs mean trouble. Is behind the sofa already.", agility=2, intellect=2),
    },
    "🙏": {
        "pouncer": L("Two hands together make one target. Takes it.", strength=1, agility=2),
        "loaf": L("Is being asked for something. Continues to sit on it.", intellect=2, strength=1),
        "chonk": L("Assumes the hands are cupped to hold food for him.", strength=1, charm=2),
        "ricochet": L("Does not wait around to be asked for anything.", agility=2),
        "ghost": L("Considers the request. Grants nothing. Fades back.", intellect=2, agility=1),
        "gremlin": L("Headbutts the folded hands apart, pleased with itself.", agility=2, charm=1),
        "barger": L("Prefers to take than to ask, and demonstrates.", intellect=2, strength=1),
        "stalker": L("Watches the begging from a height, entirely unmoved.", intellect=2),
        "purrsuader": L("Accepts the plea, having engineered it in the first place.", charm=3, intellect=2),
        "tyrant": L("Being begged is correct. She may still say no.", charm=3),
        "weaver": L("Winds round the praying one until they give up and fuss her.", charm=3, agility=1),
        "dinner": L("Somebody else is begging. She begs louder, on principle.", charm=3),
        "alley": L("Knows that asking works better than taking, sometimes.", intellect=2, charm=1),
    },
    "😱": {
        "pouncer": L("Panic makes people slow. Uses this.", strength=2, agility=1),
        "loaf": L("Everyone is screaming. The Loaf has not moved an inch.", strength=2, intellect=2),
        "chonk": L("Runs, briefly, then needs to sit down and recover.", agility=1, strength=-1),
        "ricochet": L("Reaches the top of the bookcase in under a second.", agility=3),
        "ghost": L("Was the cause of the scream. Is nowhere to be found.", agility=3, intellect=1),
        "gremlin": L("Screams along, louder, without knowing what about.", charm=1, intellect=-2),
        "barger": L("Finds the source of the fright and inspects it closely.", intellect=3, strength=1),
        "stalker": L("Watched it coming and moved twenty seconds ago.", intellect=3, agility=1),
        "purrsuader": L("Is frightened attractively and is carried to safety.", charm=3),
        "tyrant": L("Screaming is undignified. She departs at walking pace.", charm=2, strength=1),
        "weaver": L("Weaves between running legs without being stepped on.", agility=3),
        "dinner": L("Screams too, but about dinner, as always.", charm=2, intellect=-1),
        "alley": L("Is behind something solid before the scream finishes.", agility=2, intellect=2),
    },
    "😳": {
        "pouncer": L("Somebody is frozen with embarrassment. Free ankles.", strength=1, agility=2),
        "loaf": L("Has never been embarrassed. Would not know how to start.", intellect=3),
        "chonk": L("Fell off something in front of everyone. Grooms furiously.", charm=1, agility=-1),
        "ricochet": L("Misjudged a jump. Pretends the whole thing was intentional.", agility=2, charm=-1),
        "ghost": L("Was seen. Being seen is the worst thing that happens to it.", agility=2, charm=-1),
        "gremlin": L("Is incapable of embarrassment and proves it again.", charm=2, intellect=-1),
        "barger": L("Got stuck halfway through. Will not discuss it.", intellect=1, strength=1),
        "stalker": L("Slipped off the shelf. Nobody may ever mention this.", intellect=1, agility=1),
        "purrsuader": L("Turns the embarrassment into sympathy within seconds.", charm=3, intellect=1),
        "tyrant": L("Did not fall. Chose to lie down. The matter is closed.", charm=3),
        "weaver": L("Trips over her own tail and winds on as if planned.", agility=2, charm=1),
        "dinner": L("Is caught eating from the wrong bowl. Continues eating.", charm=2, strength=1),
        "alley": L("Recovers instantly. Embarrassment is a luxury.", intellect=2, agility=1),
    },
}


VARIATION = chr(0xFE0F)


def normalise(char: str) -> str:
    """Emoji with and without the variation selector are the same object.

    Discord sends some reactions with a trailing U+FE0F and the catalogue stores
    bare codepoints, so 🕷️ from a reaction and 🕷 from the catalogue are two
    different strings for the same spider. Without this, every line written for
    one of those objects is simply never found.
    """
    return (char or "").replace(VARIATION, "")


def written_for(char: str, class_key: str):
    """The hand-written line for this cell, or ``None`` if it is not written yet."""
    return _INDEX.get(normalise(char), {}).get(class_key)


_INDEX = {normalise(char): lines for char, lines in WRITTEN.items()}


def progress(total_objects: int, total_classes: int) -> dict:
    """How much of the grid is genuinely written, for the panel to show."""
    cells = sum(len(v) for v in WRITTEN.values())
    return {"objects": len(WRITTEN), "cells": cells,
            "total_objects": total_objects, "total_cells": total_objects * total_classes}

# For objects nobody has written yet: the cat has no idea what it is looking at,
# which is both true and in character. One line per class, no object name in it,
# because a placeholder that pretends to know the object is exactly the filler
# this file exists to avoid.
UNSURE: dict[str, tuple] = {
    "pouncer": L("Crouches at it, unsure whether this counts as prey.", strength=1),
    "loaf": L("Has no opinion on this and is not going to develop one.", intellect=1),
    "chonk": L("Sniffs it at length, hoping it turns out to be food.", strength=1),
    "ricochet": L("Bats it once to find out what it is, then loses it.", agility=1),
    "ghost": L("Watches it from a distance and does not commit.", intellect=1),
    "gremlin": L("Does not know what it is and bites it to find out.", strength=1, intellect=-1),
    "barger": L("Turns it over twice, trying to work out how it opens.", intellect=1),
    "stalker": L("Watches it from above until it does something.", intellect=1),
    "purrsuader": L("Cannot use this yet, so works on the human instead.", charm=1),
    "tyrant": L("Does not know what it is, and claims it regardless.", charm=1),
    "weaver": L("Winds round it once, in case it is worth knowing.", agility=1),
    "dinner": L("Asks whether it is food. Nobody answers. Asks again.", charm=1),
    "alley": L("Gives it a long look and reserves judgement.", intellect=1),
}


def line_for(char: str, class_key: str):
    """The written line, or the unsure placeholder, and which one it is."""
    line = written_for(char, class_key)
    if line is not None:
        return line[0], dict(line[1]), "written"
    cell = seeded().get(normalise(char), {}).get(class_key)
    if cell:
        return cell[0], dict(cell[1]), "seeded"
    fallback = UNSURE.get(class_key)
    if fallback is None:
        return "", {}, "empty"
    return fallback[0], dict(fallback[1]), "unsure"

# --------------------------------------------------------------------------- #
#  Seeded cells
# --------------------------------------------------------------------------- #
# Every object not written above, filled in once so there is something concrete
# in every cell to edit rather than a blank. These are starting points, not
# finished lines: they know what the object is called and roughly what the class
# would do with it, and nothing more. Editing one in the panel replaces it for
# good, and an object promoted into WRITTEN above stops reading from here.
SEEDED_PATH = _pathlib.Path(__file__).resolve().parent / "data" / "reaction_seed.json"
_SEEDED: dict = {}


def seeded() -> dict:
    global _SEEDED
    if not _SEEDED:
        try:
            raw = json.loads(SEEDED_PATH.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            raw = {}
        _SEEDED = {normalise(char): cells for char, cells in raw.items()}
    return _SEEDED
