"""
Vendor Font Awesome Free's icon **paths** into the repository.

    py tools/vendor_fa_icons.py

Writes ``helpers/dodoland/faicons.py``. Run it again to add an icon or move to a
new Font Awesome release; it is the only thing that should ever edit that file.

**Why paths and not the webfont.** Font Awesome was tried here once as a webfont,
set as SVG ``<text>`` with a ``font-family``. It never rendered: no building had
an emblem and the inhabitants came out as whatever the fallback font happened to
have at those codepoints. A webfont inside an SVG fails silently, at a distance,
in exactly the part people are meant to be looking at — and it fails completely
in the two contexts that matter most here, an ``<img>`` and a fetched fragment,
where external resources are never loaded at all.

Font Awesome's artwork is not the font. Every icon is one ``<path>``, and a path
embedded in the SVG has none of those problems: no network, no font loading, no
fallback, works in every context, and scales with the drawing. So this is real
Font Awesome artwork with none of the failure mode that got it banned from this
file. ``docs/DODOLAND.md``'s rule stands as written — no webfont, no ``<text>``.

Licensing: the icons are CC BY 4.0 (Font Awesome Free). The attribution rides in
the generated module's header, which is where it stays true.
"""

from __future__ import annotations

import pathlib
import re
import sys
import urllib.error
import urllib.request

RAW = "https://raw.githubusercontent.com/FortAwesome/Font-Awesome/{ref}/svgs/solid/{slug}.svg"
REF = "6.x"
TARGET = pathlib.Path("helpers/dodoland/faicons.py")

# name in DodoLand -> Font Awesome Free "solid" slug.
#
# The sixteen names DodoLand already had come first and keep their names, so
# every building on every server that has chosen an emblem keeps the one it
# chose. What changes is what those names draw.
WANTED: dict[str, str] = {
    # --- the original vocabulary, redrawn ---------------------------------- #
    "mug": "beer-mug-empty", "book": "book-open", "shield": "shield-halved",
    "map": "map", "masks": "masks-theater", "paw": "paw", "image": "image",
    "camera": "camera", "bread": "bread-slice", "gear": "gear", "dove": "dove",
    "bottle": "wine-bottle", "scales": "scale-balanced", "door": "door-open",
    "monument": "monument", "gamepad": "gamepad",
    # --- what a place is for ------------------------------------------------ #
    "crown": "crown", "fire": "fire", "hammer": "hammer", "music": "music",
    "heart": "heart", "star": "star", "dice": "dice-d20", "tree": "tree",
    "fish": "fish", "palette": "palette", "scroll": "scroll",
    "magic": "wand-magic-sparkles", "rook": "chess-rook", "trophy": "trophy",
    "users": "users", "comments": "comments", "microphone": "microphone",
    "seedling": "seedling", "gem": "gem", "bolt": "bolt", "moon": "moon",
    "sun": "sun", "mountain": "mountain-sun", "tent": "campground",
    "church": "church", "warehouse": "warehouse", "industry": "industry",
    "landmark": "landmark", "utensils": "utensils", "cake": "cake-candles",
    "shirt": "shirt", "ghost": "ghost", "skull": "skull", "feather": "feather",
    "key": "key", "compass": "compass", "anchor": "anchor", "flask": "flask",
    "wizard": "hat-wizard", "cat": "cat", "dog": "dog", "horse": "horse",
    "bird": "crow", "kiwi": "kiwi-bird", "bug": "bug", "leaf": "leaf",
    "apple": "apple-whole", "carrot": "carrot", "drumstick": "drumstick-bite",
    "cookie": "cookie", "hotmug": "mug-hot", "chess": "chess-knight",
    "dumbbell": "dumbbell", "shop": "shop", "bell": "bell", "gift": "gift",
}

_VIEWBOX = re.compile(r'viewBox="([^"]+)"')
_PATH = re.compile(r'<path[^>]*\sd="([^"]+)"')


def fetch(slug: str) -> tuple[str, str]:
    """``(viewBox, path)`` for one icon, straight from the source repository."""
    url = RAW.format(ref=REF, slug=slug)
    with urllib.request.urlopen(url, timeout=30) as response:
        text = response.read().decode("utf-8")
    box = _VIEWBOX.search(text)
    paths = _PATH.findall(text)
    if not box or not paths:
        raise ValueError(f"{slug}: no viewBox or no path in {url}")
    # Free solid icons are a single path; join defensively rather than lose one.
    return box.group(1), " ".join(paths)


def build(icons: dict[str, tuple[str, str]]) -> str:
    rows = "".join(
        f'    "{name}": ("{box}",\n'
        f'        "{path}"),\n'
        for name, (box, path) in sorted(icons.items()))
    return f'''"""
Font Awesome Free icon paths, vendored.

**Generated by ``tools/vendor_fa_icons.py``. Do not edit by hand** — add the
icon to that script's ``WANTED`` and run it, or the next run overwrites you.

Icons: Font Awesome Free {REF} by @fontawesome — https://fontawesome.com
License: CC BY 4.0 — https://fontawesome.com/license/free
Copyright Fonticons, Inc.

Paths, not the font. A webfont inside an SVG fails silently and completely in
an ``<img>`` and in a fetched fragment, which is exactly how the emblems went
missing from every building on the map the first time this was tried. A path
has no such failure mode: no network, no loading, no fallback, and it scales
with the drawing. See ``tools/vendor_fa_icons.py`` for the whole argument.

Each entry is ``(viewBox, path data)``. Draw one with
``helpers.dodoland.townart.icon``, which handles the scaling and centring.
"""

from __future__ import annotations

ICONS: dict[str, tuple[str, str]] = {{
{rows}}}
'''


def main(argv: list[str]) -> int:
    icons: dict[str, tuple[str, str]] = {}
    missing: list[str] = []
    for name, slug in WANTED.items():
        try:
            icons[name] = fetch(slug)
            print(f"  ok   {name:12} <- {slug}")
        except (urllib.error.HTTPError, urllib.error.URLError, ValueError) as error:
            missing.append(f"{name} ({slug}): {error}")
            print(f"  MISS {name:12} <- {slug}: {error}")
    if not icons:
        print("nothing fetched; refusing to write an empty module")
        return 1
    TARGET.write_text(build(icons), encoding="utf-8")
    print(f"\nwrote {TARGET} with {len(icons)} icons")
    if missing:
        print("could not fetch:")
        for line in missing:
            print(f"  - {line}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
